---
title: "setup_keras"
output: html_document
---
```{r}
install.packages("keras")
library(keras)
keras::install_keras(tensorflow = "gpu")

```

```{r imdb poc}

imdb <- dataset_imdb(num_words = 20000)

c(c(train_data, train_labels), c(test_data, test_labels)) %<-% imdb

word_index <- dataset_imdb_word_index()
reverse_word_index <- names(word_index)

names(reverse_word_index) <- word_index

decoded_review <- sapply(train_data[[1]], function(index) {
  word <- if (index >= 3) reverse_word_index[[as.character(index - 3)]]
  if (!is.null(word)) word else "?"
})

vectorize_sequences <- function(sequences, dimension = 20000) {
  results <- matrix(0, nrow = length(sequences), ncol = dimension)
  for (i in 1:length(sequences))
    results[i, sequences[[i]]] <- 1
  results
}

x_train <- vectorize_sequences(train_data)
x_test <- vectorize_sequences(test_data)

y_train <- as.numeric(train_labels)
y_test <- as.numeric(test_labels)

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = (20000)) %>% 
  layer_dense(units = 16, activation = "relu") %>% 
  layer_dense(units = 1, activation = "sigmoid")

model %>% 
  compile(
    optimizer = "rmsprop",
    loss = "binary_crossentropy",
    metrics = c("accuracy")
  )

val_indices <- 1:20000

x_val <- x_train[val_indices, ]

partial_x_train <- x_train[-val_indices, ]

y_val <- y_train[val_indices]
partial_y_train <- y_train[-val_indices]

model %>% 
  fit(
    partial_x_train, 
    partial_y_train,
    epochs = 30,
    batch_size = 2048,
    validation_data = list(x_val, y_val)
  )

```